/** (c) 2024 UMSATS
 * @file can_wrapper_status.h
 */

#ifndef TSAT_UTILITIES_KIT_INC_TUK_CAN_WRAPPER_CAN_WRAPPER_STATUS_H_
#define TSAT_UTILITIES_KIT_INC_TUK_CAN_WRAPPER_CAN_WRAPPER_STATUS_H_

#include <stm32l4xx.h>
#include <stm32l4xx_hal_def.h>

typedef enum
{
	CAN_WRAPPER_HAL_OK = HAL_OK,
	CAN_WRAPPER_HAL_ERROR,
	CAN_WRAPPER_HAL_BUSY,
	CAN_WRAPPER_HAL_TIMEOUT,
	CAN_WRAPPER_NULL_ARG,
	CAN_WRAPPER_ARG_OUT_OF_RANGE,
	CAN_WRAPPER_INVALID_ARG,
	CAN_WRAPPER_NOT_INITIALISED,
	CAN_WRAPPER_FAILED_TO_CONFIG_FILTER,
	CAN_WRAPPER_FAILED_TO_START_CAN,
	CAN_WRAPPER_FAILED_TO_ENABLE_INTERRUPT,
	CAN_WRAPPER_FAILED_TO_START_TIMER,
	CAN_WRAPPER_TX_FAIL_BAD_CAN_STATE,
	CAN_WRAPPER_TX_MAILBOXES_FULL
} CANWrapper_StatusTypeDef;

#endif /* TSAT_UTILITIES_KIT_INC_TUK_CAN_WRAPPER_CAN_WRAPPER_STATUS_H_ */
